spring:
  datasource:
    url: jdbc:h2:mem:${DB_NAME:clines}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate

cors:
  allowed:
    origins: ${CORS_HOST:http://localhost:3000}
    all-methods: true
    all-headers: true
    send-credentials: true